/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lab1.h"

bool_t
xdr_answer (XDR *xdrs, answer *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->number, 2,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_params (XDR *xdrs, params *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->number, 500000,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
