/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ENTREGA2_H_RPCGEN
#define _ENTREGA2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct answer {
	float number[2];
};
typedef struct answer answer;

struct params {
	float number[500000];
	int inicio;
	int fim;
};
typedef struct params params;

#define PROG 55555555
#define VERSAO 1000
#define ARRAY_LENGTH 500000

#if defined(__STDC__) || defined(__cplusplus)
#define sort 1
extern  answer * sort_1000(params *, CLIENT *);
extern  answer * sort_1000_svc(params *, struct svc_req *);
extern int prog_1000_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sort 1
extern  answer * sort_1000();
extern  answer * sort_1000_svc();
extern int prog_1000_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_answer (XDR *, answer*);
extern  bool_t xdr_params (XDR *, params*);

#else /* K&R C */
extern bool_t xdr_answer ();
extern bool_t xdr_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ENTREGA2_H_RPCGEN */
