/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include "entrega2.h"

void merge(float originalArray[], int beginIndex, int middleIndex, int finalIndex)
{
  int firstPartSize = middleIndex - beginIndex + 1;
  int lastPartSize = finalIndex - middleIndex;
  float *firstPartArray = malloc(firstPartSize * sizeof(float));
  float *lastPartArray = malloc(lastPartSize * sizeof(float));

  for (int aux = 0; aux < firstPartSize; aux++)
    firstPartArray[aux] = originalArray[beginIndex + aux];

  for (int aux = 0; aux < lastPartSize; aux++)
  {
    lastPartArray[aux] = originalArray[middleIndex + aux + 1];
  }

  int firstPartIndex = 0, lastPartIndex = 0, generalIndex = beginIndex;

  while (firstPartIndex < firstPartSize && lastPartIndex < lastPartSize)
  {
    if (firstPartArray[firstPartIndex] <= lastPartArray[lastPartIndex])
    {
      originalArray[generalIndex++] = firstPartArray[firstPartIndex++];
    }
    else
    {
      originalArray[generalIndex++] = lastPartArray[lastPartIndex++];
    }
  }

  while (firstPartIndex < firstPartSize)
  {
    originalArray[generalIndex++] = firstPartArray[firstPartIndex++];
  }

  while (lastPartIndex < lastPartSize)
  {
    originalArray[generalIndex++] = lastPartArray[lastPartIndex++];
  }
}

void mergeSort(float originalArray[], int beginIndex, int finalIndex)
{
  if (beginIndex >= finalIndex)
    return;

  int middleIndex = (beginIndex + finalIndex) / 2;

  mergeSort(originalArray, beginIndex, middleIndex);
  mergeSort(originalArray, middleIndex + 1, finalIndex);
  merge(originalArray, beginIndex, middleIndex, finalIndex);
}

answer *
sort_1000_svc(params *argp, struct svc_req *rqstp)
{
	static answer  result;
  printf("Server recebeu uma consulta\n");

	mergeSort(argp->number, argp->inicio, argp->fim - 1);

	result.number[0] = argp->number[0];
	result.number[1] = argp->number[argp->fim - 1];
	
  printf("Resultados foram contabilizados\nRetornando...\n");
  printf("----------------------------------------------\n");
	return &result;
}
